#!/bin/bash
	apk add --quiet eudev udev-init-scripts udev-init-scripts-openrc
	rc-update add --quiet udev sysinit
	rc-update add --quiet udev-trigger sysinit
	rc-update add --quiet udev-settle sysinit
	rc-update add --quiet udev-postmount default
	rc-service --ifstopped udev start
	rc-service --ifstopped udev-trigger start
	rc-service --ifstopped udev-settle start
	rc-service --ifstopped udev-postmount start
